### ISSUE TITLE
Define product roadmap

### ISSUE THREAD

**Issue by zacharlie** [kartoza/geodata-mart#1]
Define a product development road map that outlines expected milestones, targets, and strategy for development

**Comment by zacharlie** [comment]
The product should be capable of being developed in discrete components, however each component and milestone should be developed in a manner that envisions the overarching project design.

- [ ] - 1\. Develop a basic data clipping utility for downloading spatial information
- [ ] - 2\. Extend the data clipping utility with additional customisations (e.g. user defined regions)
- [ ] - 3\. Extend the data clipping utility for data processing and enrichment
- [ ] - 4\. Integration of this process with additional tools or platform (e.g. GeoContext/ OSGS)
- [ ] - 5\. Provide support for additional datasets
- [ ] - 6\. Provide support for independent vendors
- [ ] - 7\. Expose this functionality to the public programmatically for additional integration into other tools (e.g. QGIS)
- [ ] - 8\. Develop a cataloguing platform for browsing, processing, and retrieving spatial data from various sources

**Comment by zacharlie** [comment]
Many of these considerations deeply affected the platform data modelling process and have been implemented internally from the outset, but will need extension to support external application integration
